### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mordamax**

### CODE REVIEW

**Comment by mordamax** [comment]
bot rebase

**Comment by mordamax** [comment]
bot rebase

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak-rebase-merge

**Comment by mordamax** [comment]
bot merge -v PIPELINE_SCRIPTS_REF=mak-rebase-merge

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak-rebase-merge

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak-rebase-merge

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak-rebase-merge

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak-rebase-merge

**Comment by mordamax** [comment]
bot help

**Comment by mordamax** [comment]
lbot help

**Comment by mordamax** [comment]
lbot help

**Comment by mordamax** [comment]
lbot help

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot help

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
doesn't have a command

**Comment by mordamax** [comment]
bot help

**Comment by mordamax** [comment]
lbot help

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
random one

**Comment by mordamax** [comment]
bot help

**Comment by mordamax** [comment]
lbot help

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
random shit

**Comment by mordamax** [comment]
lbot help

**Comment by mordamax** [comment]
lbot something

**Comment by mordamax** [comment]
lbot clean

**Comment by mordamax** [comment]
lbot clean --all

**Comment by mordamax** [comment]
lbot clean --all

**Comment by mordamax** [comment]
lbot clean --all

**Comment by mordamax** [comment]
lbot clean --all

**Comment by mak-parity** [comment]
whatup

**Comment by mak-parity** [comment]
lbot help

**Comment by mak-parity** [comment]
lbot clean --all

**Comment by mak-parity** [comment]
bla bla

**Comment by mak-parity** [comment]
lbot clean --all

**Comment by mak-parity** [comment]
lbot something

**Comment by mak-parity** [comment]
lbot clean

**Comment by mak-parity** [comment]
lbot clean --all

**Comment by mak-parity** [comment]
lbot help

**Comment by mak-parity** [comment]
lbot help

**Pull request closed without merging**
